local _, L = ...;

if GetLocale() == "esMX" then
	-- L["Actions"] = ""
	-- L["Are you sure you want to delete filter set?"] = ""
	L["At least one word"] = "Por lo menos una palabra"
	-- L["Enable sound notifications"] = ""
	-- L["Enter filter set name"] = ""
	L["Exclude words"] = "Palabras para excluir"
	L["EXPERIMENTAL"] = "EXPERIMENTAL"
	-- L["Filter set"] = ""
	-- L["found new group"] = ""
	-- L["found new player"] = ""
	L["Include words"] = "Palabras para incluir"
	-- L["Monitoring"] = ""
	-- L["Monitor new groups in background?"] = ""
	-- L["More"] = ""
	-- L["More options"] = ""
	-- L["New filter set"] = ""
	-- L["New version available"] = ""
	-- L["Notifications"] = ""
	-- L["Notify in chat on new group"] = ""
	-- L["Notify in chat on new player"] = ""
	L["The words you don't want"] = "Palabras no deseadas"
	L["The words you want"] = "Palabras deseadas"
	-- L["Update interval (sec.)"] = ""
	-- L["Works only on premades created with Premade Filter addon"] = ""
	L["You want at least one of these words"] = "Quieres por lo menos una de estas palabras"
end
