local _, L = ...

if GetLocale() ~= "esMX" then
	return
end

--[[Translation missing --]]
--[[ L["Actions"] = "Actions"--]]
--[[Translation missing --]]
--[[ L["Alive"] = "Alive"--]]
--[[Translation missing --]]
--[[ L["Any"] = "Any"--]]
--[[Translation missing --]]
--[[ L["Are you sure you want to delete filter set?"] = "Are you sure you want to delete filter set?"--]]
L["At least one word"] = "Por lo menos una palabra"
--[[Translation missing --]]
--[[ L["Attention! Update interval shorter than 15 seconds may cause the game to run slow and impact your gaming experience!!!"] = "Attention! Update interval shorter than 15 seconds may cause the game to run slow and impact your gaming experience!!!"--]]
--[[Translation missing --]]
--[[ L["Boss status colors"] = "Boss status colors"--]]
--[[Translation missing --]]
--[[ L["By hiding the window you can activate background search so you can do anything else in the game."] = "By hiding the window you can activate background search so you can do anything else in the game."--]]
--[[Translation missing --]]
--[[ L["Click [+] to open window within extended features."] = "Click [+] to open window within extended features."--]]
--[[Translation missing --]]
--[[ L["Defeated"] = "Defeated"--]]
--[[Translation missing --]]
--[[ L["Define minimum and/or maximum number of players of any role."] = "Define minimum and/or maximum number of players of any role."--]]
--[[Translation missing --]]
--[[ L["Enable sound notifications"] = "Enable sound notifications"--]]
--[[Translation missing --]]
--[[ L["Enter filter set name"] = "Enter filter set name"--]]
--[[Translation missing --]]
--[[ L["Enter the words you want to be present or absent in group title and comment."] = "Enter the words you want to be present or absent in group title and comment."--]]
L["Exclude words"] = "Palabras para excluir"
L["EXPERIMENTAL"] = "EXPERIMENTAL"
--[[Translation missing --]]
--[[ L["Filter set"] = "Filter set"--]]
--[[Translation missing --]]
--[[ L["For example if you are a tank you can set maximum number of tanks to 1 and you get the groups you are guaranteed to have a spot."] = "For example if you are a tank you can set maximum number of tanks to 1 and you get the groups you are guaranteed to have a spot."--]]
--[[Translation missing --]]
--[[ L["found new group"] = "found new group"--]]
--[[Translation missing --]]
--[[ L["found new player"] = "found new player"--]]
--[[Translation missing --]]
--[[ L["If a group is not created by the addon this option is ignored."] = "If a group is not created by the addon this option is ignored."--]]
--[[Translation missing --]]
--[[ L["If you want to join a group of highly equipped characters you can setup minimum item level defined for its members."] = "If you want to join a group of highly equipped characters you can setup minimum item level defined for its members."--]]
L["Include words"] = "Palabras para incluir"
--[[Translation missing --]]
--[[ L["Monitor new groups in background?"] = "Monitor new groups in background?"--]]
--[[Translation missing --]]
--[[ L["Monitoring"] = "Monitoring"--]]
--[[Translation missing --]]
--[[ L["More"] = "More"--]]
--[[Translation missing --]]
--[[ L["More options"] = "More options"--]]
--[[Translation missing --]]
--[[ L["New filter set"] = "New filter set"--]]
--[[Translation missing --]]
--[[ L["New version available"] = "New version available"--]]
--[[Translation missing --]]
--[[ L["Notifications"] = "Notifications"--]]
--[[Translation missing --]]
--[[ L["Notify in chat on new group"] = "Notify in chat on new group"--]]
--[[Translation missing --]]
--[[ L["Notify in chat on new player"] = "Notify in chat on new player"--]]
--[[Translation missing --]]
--[[ L["Select group activity: quest, dungeon, raid, difficulty"] = "Select group activity: quest, dungeon, raid, difficulty"--]]
--[[Translation missing --]]
--[[ L["Select the roles you can fulfill."] = "Select the roles you can fulfill."--]]
--[[Translation missing --]]
--[[ L["The addon notifies you if it finds a group that matches your requirements."] = "The addon notifies you if it finds a group that matches your requirements."--]]
--[[Translation missing --]]
--[[ L["The filters take effect when you click this button. The changes don't take effect until you do that."] = "The filters take effect when you click this button. The changes don't take effect until you do that."--]]
L["The words you don't want"] = "Palabras no deseadas"
L["The words you want"] = "Palabras deseadas"
--[[Translation missing --]]
--[[ L["Update interval (sec.)"] = "Update interval (sec.)"--]]
--[[Translation missing --]]
--[[ L["Want to find a mythic raid? Choose your realm only."] = "Want to find a mythic raid? Choose your realm only."--]]
--[[Translation missing --]]
--[[ L["Works only on premades created with Premade Filter addon"] = "Works only on premades created with Premade Filter addon"--]]
--[[Translation missing --]]
--[[ L["You can find a group that uses specific voice chat software or a group tha doesn't use voice chat at all."] = "You can find a group that uses specific voice chat software or a group tha doesn't use voice chat at all."--]]
--[[Translation missing --]]
--[[ L["You can mark the bosses you want to be still alive with [v] and the bosses you want to be already defeated by [-]."] = "You can mark the bosses you want to be still alive with [v] and the bosses you want to be already defeated by [-]."--]]
--[[Translation missing --]]
--[[ L["You can save the filters to use them in future."] = "You can save the filters to use them in future."--]]
L["You want at least one of these words"] = "Quieres por lo menos una de estas palabras"
