local _, L = ...

if GetLocale() ~= "frFR" then
	return
end

--Translation missing
-- L["Actions"] = ""
--Translation missing
-- L["Alive"] = ""
--Translation missing
-- L["Any"] = ""
--Translation missing
-- L["Are you sure you want to delete filter set?"] = ""
--Translation missing
-- L["At least one word"] = ""
--Translation missing
-- L["Attention! Update interval shorter than 15 seconds may cause the game to run slow and impact your gaming experience!!!"] = ""
--Translation missing
-- L["Boss status colors"] = ""
--Translation missing
-- L["By hiding the window you can activate background search so you can do anything else in the game."] = ""
--Translation missing
-- L["Click [+] to open window within extended features."] = ""
--Translation missing
-- L["Defeated"] = ""
--Translation missing
-- L["Define minimum and/or maximum number of players of any role."] = ""
--Translation missing
-- L["Enable sound notifications"] = ""
--Translation missing
-- L["Enter filter set name"] = ""
--Translation missing
-- L["Enter the words you want to be present or absent in group title and comment."] = ""
--Translation missing
-- L["Exclude words"] = ""
--Translation missing
-- L["EXPERIMENTAL"] = ""
--Translation missing
-- L["Filter set"] = ""
--Translation missing
-- L["For example if you are a tank you can set maximum number of tanks to 1 and you get the groups you are guaranteed to have a spot."] = ""
--Translation missing
-- L["found new group"] = ""
--Translation missing
-- L["found new player"] = ""
--Translation missing
-- L["If a group is not created by the addon this option is ignored."] = ""
--Translation missing
-- L["If you want to join a group of highly equipped characters you can setup minimum item level defined for its members."] = ""
--Translation missing
-- L["Include words"] = ""
--Translation missing
-- L["Monitor new groups in background?"] = ""
--Translation missing
-- L["Monitoring"] = ""
--Translation missing
-- L["More"] = ""
--Translation missing
-- L["More options"] = ""
--Translation missing
-- L["New filter set"] = ""
--Translation missing
-- L["New version available"] = ""
--Translation missing
-- L["Notifications"] = ""
--Translation missing
-- L["Notify in chat on new group"] = ""
--Translation missing
-- L["Notify in chat on new player"] = ""
--Translation missing
-- L["Select group activity: quest, dungeon, raid, difficulty"] = ""
--Translation missing
-- L["Select the roles you can fulfill."] = ""
--Translation missing
-- L["The addon notifies you if it finds a group that matches your requirements."] = ""
--Translation missing
-- L["The filters take effect when you click this button. The changes don't take effect until you do that."] = ""
--Translation missing
-- L["The words you don't want"] = ""
--Translation missing
-- L["The words you want"] = ""
--Translation missing
-- L["Update interval (sec.)"] = ""
--Translation missing
-- L["Want to find a mythic raid? Choose your realm only."] = ""
--Translation missing
-- L["Works only on premades created with Premade Filter addon"] = ""
--Translation missing
-- L["You can find a group that uses specific voice chat software or a group tha doesn't use voice chat at all."] = ""
--Translation missing
-- L["You can mark the bosses you want to be still alive with [v] and the bosses you want to be already defeated by [-]."] = ""
--Translation missing
-- L["You can save the filters to use them in future."] = ""
--Translation missing
-- L["You want at least one of these words"] = ""
