local _, L = ...;

if GetLocale() == "ruRU" then
	L["Actions"] = "Действия"
	L["Alive"] = "Жив"
	L["Any"] = "Любой"
	L["Are you sure you want to delete filter set?"] = "Вы действительно хотите удалить набор фильтров?"
	L["At least one word"] = "Любое из слов"
	L["Boss status colors"] = "Цветовые статусы боссов"
	L["Defeated"] = "Убит"
	L["Enable sound notifications"] = "Включить звуковые оповещения"
	L["Enter filter set name"] = "Введите название набора фильтров"
	L["Exclude words"] = "Исключить слова"
	L["EXPERIMENTAL"] = "ЭКСПЕРЕМЕНТАЛЬНО"
	L["Filter set"] = "Набор фильтров"
	L["found new group"] = "найдена новая группа"
	L["found new player"] = "найден новый игрок"
	L["Include words"] = "Включить слова"
	L["Monitoring"] = "Отслеживание"
	L["Monitor new groups in background?"] = "Отслеживать новые группы в фоновом режиме?"
	L["More"] = "Еще"
	L["More options"] = "Дополнительно"
	L["New filter set"] = "Новый набор фильтров"
	L["New version available"] = "Доступна новая версия"
	L["Notifications"] = "Оповещения"
	L["Notify in chat on new group"] = "Оповещать в чат о новой группе"
	L["Notify in chat on new player"] = "Оповещать в чат о новом игроке"
	L["The words you don't want"] = "Ненужные вам слова"
	L["The words you want"] = "Нужные вам слова"
	L["Update interval (sec.)"] = "Интервал обновления (сек.)"
	L["Works only on premades created with Premade Filter addon"] = "Работает только для премейдов, созданных с помощью аддона Premade Filter"
	L["You want at least one of these words"] = "Вам нужно как минимум одно из этих слов"
end
