local _, L = ...;

if GetLocale() == "zhCN" then
	L["Actions"] = "动作"
	L["Alive"] = "存活"
	L["Any"] = "任何"
	L["Are you sure you want to delete filter set?"] = "您确定要删除筛选设置吗？"
	L["At least one word"] = "至少一个字"
	L["Boss status colors"] = "首领状态颜色"
	L["Defeated"] = "已击杀"
	L["Enable sound notifications"] = "启用声音提醒"
	L["Enter filter set name"] = "输入筛选设置名称"
	L["Exclude words"] = "排除的文字"
	L["EXPERIMENTAL"] = "实验"
	L["Filter set"] = "筛选设置"
	L["found new group"] = "找到新的团队"
	L["found new player"] = "找到新的玩家"
	L["Include words"] = "包含的文字"
	L["Monitoring"] = "监控"
	L["Monitor new groups in background?"] = "在后台中监控新的团队吗？"
	L["More"] = "更多"
	L["More options"] = "更多选项"
	L["New filter set"] = "新的筛选设置"
	L["New version available"] = "新的版本可用"
	L["Notifications"] = "提醒"
	L["Notify in chat on new group"] = "在聊天中提醒新团队"
	L["Notify in chat on new player"] = "在聊天中提醒新玩家"
	L["The words you don't want"] = "你不想要的文字"
	L["The words you want"] = "你想要的文字"
	L["Update interval (sec.)"] = "更新间隔(秒)"
	L["Works only on premades created with Premade Filter addon"] = "只有运作在预组筛选插件创建的预组队伍"
	L["You want at least one of these words"] = "你想要的至少其中一个字"
end
