local _, L = ...;

if GetLocale() == "zhTW" then
	L["Actions"] = "動作"
	-- L["Alive"] = ""
	-- L["Any"] = ""
	L["Are you sure you want to delete filter set?"] = "您確定要刪除篩選設置嗎？"
	L["At least one word"] = "至少一個字"
	-- L["Boss status colors"] = ""
	-- L["Defeated"] = ""
	L["Enable sound notifications"] = "啟用聲音提醒"
	L["Enter filter set name"] = "輸入篩選設置名稱"
	L["Exclude words"] = "排除的文字"
	L["EXPERIMENTAL"] = "實驗"
	L["Filter set"] = "篩選設置"
	L["found new group"] = "找到新的團隊"
	L["found new player"] = "找到新的玩家"
	L["Include words"] = "包含的文字"
	L["Monitoring"] = "監控"
	L["Monitor new groups in background?"] = "在背景中監控新的團隊嗎？"
	L["More"] = "更多"
	L["More options"] = "更多選項"
	L["New filter set"] = "新的篩選設置"
	L["New version available"] = "新的版本可用"
	L["Notifications"] = "提醒"
	L["Notify in chat on new group"] = "在聊天中提醒新團隊"
	L["Notify in chat on new player"] = "在聊天中提醒新玩家"
	L["The words you don't want"] = "你不想要的文字"
	L["The words you want"] = "你想要的文字"
	L["Update interval (sec.)"] = "更新間隔(秒)"
	L["Works only on premades created with Premade Filter addon"] = "只有運作在預組篩選插件創建的預組隊伍"
	L["You want at least one of these words"] = "你想要的至少其中一個字"
end
